services:
  - type: web
    name: sr-dashboard
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: echo done
    startCommand: python server.py
    rootDir: files
    envVars:
      - key: PORT
        value: 10000
        
